# Generated by Django 2.2.12 on 2020-04-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200430_1116'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='song_history',
            field=models.ManyToManyField(to='quiz.Song'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='spotify_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
