# Generated by Django 2.2.12 on 2020-05-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200430_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='song_history',
            field=models.ManyToManyField(null=True, to='quiz.Song'),
        ),
    ]
