# Generated by Django 2.2.12 on 2020-04-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('download_url', models.URLField()),
                ('cover', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
