# Generated by Django 2.2.12 on 2020-04-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200430_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
