# Generated by Django 2.2.12 on 2020-05-08 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='song',
            name='cover',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('answer', models.CharField(default='', max_length=150)),
                ('gameID', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_players', models.IntegerField(default=0)),
                ('game_state', models.CharField(default='Waiting in lobby', max_length=20)),
                ('num_answers', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('players', models.ManyToManyField(to='quiz.Player')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.Album'),
            preserve_default=False,
        ),
    ]
