# Generated by Django 2.2.12 on 2020-05-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200508_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.GameInfo')),
                ('radio', models.ManyToManyField(to='quiz.Song')),
            ],
        ),
    ]
