# Generated by Django 2.2.12 on 2020-05-08 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='quiz.Song'),
        ),
    ]
