# Generated by Django 2.2.12 on 2020-05-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200508_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='gameID',
            new_name='game_id',
        ),
    ]
