# Generated by Django 2.2.12 on 2020-05-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200508_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
