# Generated by Django 2.2.12 on 2020-05-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200508_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
