# Generated by Django 2.2.12 on 2020-05-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20200513_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
