# Generated by Django 2.2.12 on 2020-05-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_player_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deezer_id', models.IntegerField()),
                ('picture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='password',
        ),
        migrations.RemoveField(
            model_name='game',
            name='private',
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField()),
                ('private', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('words', models.TextField(blank=True)),
                ('game_type', models.ManyToManyField(to='quiz.GameTypes')),
                ('genre', models.ManyToManyField(to='quiz.Genre')),
            ],
        ),
    ]
