# Generated by Django 2.2.12 on 2020-05-13 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20200513_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='settings',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.GameSettings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='rounds',
            field=models.IntegerField(default=15),
        ),
    ]
