# Generated by Django 2.2.12 on 2020-05-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20200514_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='game_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.GameTypes'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='genre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.Genre'),
        ),
    ]
