# Generated by Django 2.2.12 on 2020-05-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_genre_tracklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
