# Generated by Django 2.2.12 on 2020-05-24 19:48

from django.db import migrations, models
import django.db.models.deletion
import quiz.basemodels


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_gameinfo_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='game_type',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.GameTypes'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='genre',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Genre'),
        ),
    ]
