# Generated by Django 2.2.12 on 2020-05-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20200524_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='game_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.GameTypes'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Genre'),
        ),
    ]
