# Generated by Django 2.2.12 on 2020-05-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20200524_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
